// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createPoll, deletePollById, getAllPolls, getPollById, getVotesForPoll, login, logout, type Options, readUsersMe, registerUser, submitVote } from '../sdk.gen';
import type { CreatePollData, CreatePollError, DeletePollByIdData, DeletePollByIdError, DeletePollByIdResponse, GetAllPollsData, GetPollByIdData, GetVotesForPollData, LoginData, LoginError, LoginResponse, LogoutData, LogoutResponse, ReadUsersMeData, RegisterUserData, RegisterUserError, RegisterUserResponse, SubmitVoteData, SubmitVoteError } from '../types.gen';

/**
 * Register User
 */
export const registerUserMutation = (options?: Partial<Options<RegisterUserData>>): UseMutationOptions<RegisterUserResponse, RegisterUserError, Options<RegisterUserData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserResponse, RegisterUserError, Options<RegisterUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const loginMutation = (options?: Partial<Options<LoginData>>): UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> => {
    const mutationOptions: UseMutationOptions<LoginResponse, LoginError, Options<LoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await login({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutMutation = (options?: Partial<Options<LogoutData>>): UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> => {
    const mutationOptions: UseMutationOptions<LogoutResponse, DefaultError, Options<LogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const readUsersMeQueryKey = (options?: Options<ReadUsersMeData>) => createQueryKey('readUsersMe', options);

/**
 * Read Users Me
 */
export const readUsersMeOptions = (options?: Options<ReadUsersMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readUsersMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readUsersMeQueryKey(options)
    });
};

/**
 * Create Poll
 */
export const createPollMutation = (options?: Partial<Options<CreatePollData>>): UseMutationOptions<unknown, CreatePollError, Options<CreatePollData>> => {
    const mutationOptions: UseMutationOptions<unknown, CreatePollError, Options<CreatePollData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPoll({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllPollsQueryKey = (options?: Options<GetAllPollsData>) => createQueryKey('getAllPolls', options);

/**
 * Get All Polls
 */
export const getAllPollsOptions = (options?: Options<GetAllPollsData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllPolls({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAllPollsQueryKey(options)
    });
};

/**
 * Delete Poll By Id
 */
export const deletePollByIdMutation = (options?: Partial<Options<DeletePollByIdData>>): UseMutationOptions<DeletePollByIdResponse, DeletePollByIdError, Options<DeletePollByIdData>> => {
    const mutationOptions: UseMutationOptions<DeletePollByIdResponse, DeletePollByIdError, Options<DeletePollByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePollById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPollByIdQueryKey = (options: Options<GetPollByIdData>) => createQueryKey('getPollById', options);

/**
 * Get Poll By Id
 */
export const getPollByIdOptions = (options: Options<GetPollByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPollById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPollByIdQueryKey(options)
    });
};

/**
 * Submit Vote
 */
export const submitVoteMutation = (options?: Partial<Options<SubmitVoteData>>): UseMutationOptions<unknown, SubmitVoteError, Options<SubmitVoteData>> => {
    const mutationOptions: UseMutationOptions<unknown, SubmitVoteError, Options<SubmitVoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await submitVote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getVotesForPollQueryKey = (options: Options<GetVotesForPollData>) => createQueryKey('getVotesForPoll', options);

/**
 * Get Votes For Poll
 */
export const getVotesForPollOptions = (options: Options<GetVotesForPollData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVotesForPoll({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getVotesForPollQueryKey(options)
    });
};
