// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createPollPollCreatePost, deletePollByIdPollPollIdDelete, getAllPollsPollAllGet, getPollByIdPollPollIdGet, loginUserLoginPost, logoutUserLogoutPost, type Options, readUsersMeUserMeGet, registerUserUserRegisterPost } from '../sdk.gen';
import type { CreatePollPollCreatePostData, CreatePollPollCreatePostError, DeletePollByIdPollPollIdDeleteData, DeletePollByIdPollPollIdDeleteError, DeletePollByIdPollPollIdDeleteResponse, GetAllPollsPollAllGetData, GetPollByIdPollPollIdGetData, LoginUserLoginPostData, LoginUserLoginPostError, LoginUserLoginPostResponse, LogoutUserLogoutPostData, LogoutUserLogoutPostResponse, ReadUsersMeUserMeGetData, RegisterUserUserRegisterPostData, RegisterUserUserRegisterPostError, RegisterUserUserRegisterPostResponse } from '../types.gen';

/**
 * Register User
 */
export const registerUserUserRegisterPostMutation = (options?: Partial<Options<RegisterUserUserRegisterPostData>>): UseMutationOptions<RegisterUserUserRegisterPostResponse, RegisterUserUserRegisterPostError, Options<RegisterUserUserRegisterPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterUserUserRegisterPostResponse, RegisterUserUserRegisterPostError, Options<RegisterUserUserRegisterPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await registerUserUserRegisterPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Login
 */
export const loginUserLoginPostMutation = (options?: Partial<Options<LoginUserLoginPostData>>): UseMutationOptions<LoginUserLoginPostResponse, LoginUserLoginPostError, Options<LoginUserLoginPostData>> => {
    const mutationOptions: UseMutationOptions<LoginUserLoginPostResponse, LoginUserLoginPostError, Options<LoginUserLoginPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginUserLoginPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Logout
 */
export const logoutUserLogoutPostMutation = (options?: Partial<Options<LogoutUserLogoutPostData>>): UseMutationOptions<LogoutUserLogoutPostResponse, DefaultError, Options<LogoutUserLogoutPostData>> => {
    const mutationOptions: UseMutationOptions<LogoutUserLogoutPostResponse, DefaultError, Options<LogoutUserLogoutPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutUserLogoutPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const readUsersMeUserMeGetQueryKey = (options?: Options<ReadUsersMeUserMeGetData>) => createQueryKey('readUsersMeUserMeGet', options);

/**
 * Read Users Me
 */
export const readUsersMeUserMeGetOptions = (options?: Options<ReadUsersMeUserMeGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await readUsersMeUserMeGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: readUsersMeUserMeGetQueryKey(options)
    });
};

/**
 * Create Poll
 */
export const createPollPollCreatePostMutation = (options?: Partial<Options<CreatePollPollCreatePostData>>): UseMutationOptions<unknown, CreatePollPollCreatePostError, Options<CreatePollPollCreatePostData>> => {
    const mutationOptions: UseMutationOptions<unknown, CreatePollPollCreatePostError, Options<CreatePollPollCreatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPollPollCreatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getAllPollsPollAllGetQueryKey = (options?: Options<GetAllPollsPollAllGetData>) => createQueryKey('getAllPollsPollAllGet', options);

/**
 * Get All Polls
 */
export const getAllPollsPollAllGetOptions = (options?: Options<GetAllPollsPollAllGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAllPollsPollAllGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAllPollsPollAllGetQueryKey(options)
    });
};

/**
 * Delete Poll By Id
 */
export const deletePollByIdPollPollIdDeleteMutation = (options?: Partial<Options<DeletePollByIdPollPollIdDeleteData>>): UseMutationOptions<DeletePollByIdPollPollIdDeleteResponse, DeletePollByIdPollPollIdDeleteError, Options<DeletePollByIdPollPollIdDeleteData>> => {
    const mutationOptions: UseMutationOptions<DeletePollByIdPollPollIdDeleteResponse, DeletePollByIdPollPollIdDeleteError, Options<DeletePollByIdPollPollIdDeleteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deletePollByIdPollPollIdDelete({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getPollByIdPollPollIdGetQueryKey = (options: Options<GetPollByIdPollPollIdGetData>) => createQueryKey('getPollByIdPollPollIdGet', options);

/**
 * Get Poll By Id
 */
export const getPollByIdPollPollIdGetOptions = (options: Options<GetPollByIdPollPollIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPollByIdPollPollIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPollByIdPollPollIdGetQueryKey(options)
    });
};
