// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePollData, CreatePollErrors, CreatePollResponses, DeletePollByIdData, DeletePollByIdErrors, DeletePollByIdResponses, GetAllPollsData, GetAllPollsResponses, GetPollByIdData, GetPollByIdErrors, GetPollByIdResponses, GetVotesForPollData, GetVotesForPollErrors, GetVotesForPollResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, ReadUsersMeData, ReadUsersMeResponses, RegisterUserData, RegisterUserErrors, RegisterUserResponses, SubmitVoteData, SubmitVoteErrors, SubmitVoteResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register User
 */
export const registerUser = <ThrowOnError extends boolean = false>(options: Options<RegisterUserData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterUserResponses, RegisterUserErrors, ThrowOnError>({
        url: '/user/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: '/user/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
        url: '/user/logout',
        ...options
    });
};

/**
 * Read Users Me
 */
export const readUsersMe = <ThrowOnError extends boolean = false>(options?: Options<ReadUsersMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadUsersMeResponses, unknown, ThrowOnError>({
        url: '/user/me',
        ...options
    });
};

/**
 * Create Poll
 */
export const createPoll = <ThrowOnError extends boolean = false>(options: Options<CreatePollData, ThrowOnError>) => {
    return (options.client ?? client).post<CreatePollResponses, CreatePollErrors, ThrowOnError>({
        url: '/poll/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get All Polls
 */
export const getAllPolls = <ThrowOnError extends boolean = false>(options?: Options<GetAllPollsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllPollsResponses, unknown, ThrowOnError>({
        url: '/poll/all',
        ...options
    });
};

/**
 * Delete Poll By Id
 */
export const deletePollById = <ThrowOnError extends boolean = false>(options: Options<DeletePollByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeletePollByIdResponses, DeletePollByIdErrors, ThrowOnError>({
        url: '/poll/{poll_id}',
        ...options
    });
};

/**
 * Get Poll By Id
 */
export const getPollById = <ThrowOnError extends boolean = false>(options: Options<GetPollByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetPollByIdResponses, GetPollByIdErrors, ThrowOnError>({
        url: '/poll/{poll_id}',
        ...options
    });
};

/**
 * Submit Vote
 */
export const submitVote = <ThrowOnError extends boolean = false>(options: Options<SubmitVoteData, ThrowOnError>) => {
    return (options.client ?? client).post<SubmitVoteResponses, SubmitVoteErrors, ThrowOnError>({
        url: '/vote/submit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Votes For Poll
 */
export const getVotesForPoll = <ThrowOnError extends boolean = false>(options: Options<GetVotesForPollData, ThrowOnError>) => {
    return (options.client ?? client).get<GetVotesForPollResponses, GetVotesForPollErrors, ThrowOnError>({
        url: '/vote/{poll_id}',
        ...options
    });
};
