// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePollPollCreatePostData, CreatePollPollCreatePostErrors, CreatePollPollCreatePostResponses, DeletePollByIdPollPollIdDeleteData, DeletePollByIdPollPollIdDeleteErrors, DeletePollByIdPollPollIdDeleteResponses, GetAllPollsPollAllGetData, GetAllPollsPollAllGetResponses, GetPollByIdPollPollIdGetData, GetPollByIdPollPollIdGetErrors, GetPollByIdPollPollIdGetResponses, LoginUserLoginPostData, LoginUserLoginPostErrors, LoginUserLoginPostResponses, LogoutUserLogoutPostData, LogoutUserLogoutPostResponses, ReadUsersMeUserMeGetData, ReadUsersMeUserMeGetResponses, RegisterUserUserRegisterPostData, RegisterUserUserRegisterPostErrors, RegisterUserUserRegisterPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register User
 */
export const registerUserUserRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterUserUserRegisterPostData, ThrowOnError>) => {
    return (options.client ?? client).post<RegisterUserUserRegisterPostResponses, RegisterUserUserRegisterPostErrors, ThrowOnError>({
        url: '/user/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login
 */
export const loginUserLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginUserLoginPostData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginUserLoginPostResponses, LoginUserLoginPostErrors, ThrowOnError>({
        url: '/user/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Logout
 */
export const logoutUserLogoutPost = <ThrowOnError extends boolean = false>(options?: Options<LogoutUserLogoutPostData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutUserLogoutPostResponses, unknown, ThrowOnError>({
        url: '/user/logout',
        ...options
    });
};

/**
 * Read Users Me
 */
export const readUsersMeUserMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUsersMeUserMeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadUsersMeUserMeGetResponses, unknown, ThrowOnError>({
        url: '/user/me',
        ...options
    });
};

/**
 * Create Poll
 */
export const createPollPollCreatePost = <ThrowOnError extends boolean = false>(options: Options<CreatePollPollCreatePostData, ThrowOnError>) => {
    return (options.client ?? client).post<CreatePollPollCreatePostResponses, CreatePollPollCreatePostErrors, ThrowOnError>({
        url: '/poll/create',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get All Polls
 */
export const getAllPollsPollAllGet = <ThrowOnError extends boolean = false>(options?: Options<GetAllPollsPollAllGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetAllPollsPollAllGetResponses, unknown, ThrowOnError>({
        url: '/poll/all',
        ...options
    });
};

/**
 * Delete Poll By Id
 */
export const deletePollByIdPollPollIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeletePollByIdPollPollIdDeleteData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeletePollByIdPollPollIdDeleteResponses, DeletePollByIdPollPollIdDeleteErrors, ThrowOnError>({
        url: '/poll/{poll_id}',
        ...options
    });
};

/**
 * Get Poll By Id
 */
export const getPollByIdPollPollIdGet = <ThrowOnError extends boolean = false>(options: Options<GetPollByIdPollPollIdGetData, ThrowOnError>) => {
    return (options.client ?? client).get<GetPollByIdPollPollIdGetResponses, GetPollByIdPollPollIdGetErrors, ThrowOnError>({
        url: '/poll/{poll_id}',
        ...options
    });
};
