// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * CreatePollPayload
 */
export type CreatePollPayload = {
    /**
     * Question
     */
    question: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * CreateUserPayload
 */
export type CreateUserPayload = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * GetPollRow
 */
export type GetPollRow = {
    /**
     * Id
     */
    id: number;
    /**
     * Question
     */
    question: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Creator Name
     */
    creator_name: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Option Ids
     */
    option_ids: Array<number>;
};

/**
 * GetPollsRow
 */
export type GetPollsRow = {
    /**
     * Id
     */
    id: number;
    /**
     * Question
     */
    question: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Creator Name
     */
    creator_name: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Option Ids
     */
    option_ids: Array<number>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginPayload
 */
export type LoginPayload = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterUserData = {
    body: CreateUserPayload;
    path?: never;
    query?: never;
    url: '/user/register';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    201: UserInfo;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type LoginData = {
    body: LoginPayload;
    path?: never;
    query?: never;
    url: '/user/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type ReadUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type ReadUsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type ReadUsersMeResponse = ReadUsersMeResponses[keyof ReadUsersMeResponses];

export type CreatePollData = {
    body: CreatePollPayload;
    path?: never;
    query?: never;
    url: '/poll/create';
};

export type CreatePollErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePollError = CreatePollErrors[keyof CreatePollErrors];

export type CreatePollResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetAllPollsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/poll/all';
};

export type GetAllPollsResponses = {
    /**
     * Response Get All Polls Poll All Get
     *
     * Successful Response
     */
    200: Array<GetPollsRow>;
};

export type GetAllPollsResponse = GetAllPollsResponses[keyof GetAllPollsResponses];

export type DeletePollByIdData = {
    body?: never;
    path: {
        /**
         * Poll Id
         */
        poll_id: number;
    };
    query?: never;
    url: '/poll/{poll_id}';
};

export type DeletePollByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePollByIdError = DeletePollByIdErrors[keyof DeletePollByIdErrors];

export type DeletePollByIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePollByIdResponse = DeletePollByIdResponses[keyof DeletePollByIdResponses];

export type GetPollByIdData = {
    body?: never;
    path: {
        /**
         * Poll Id
         */
        poll_id: number;
    };
    query?: never;
    url: '/poll/{poll_id}';
};

export type GetPollByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPollByIdError = GetPollByIdErrors[keyof GetPollByIdErrors];

export type GetPollByIdResponses = {
    /**
     * Successful Response
     */
    200: GetPollRow;
};

export type GetPollByIdResponse = GetPollByIdResponses[keyof GetPollByIdResponses];
