// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * CreatePollPayload
 */
export type CreatePollPayload = {
    /**
     * Question
     */
    question: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Expires At
     */
    expires_at: string | null;
};

/**
 * CreateUserPayload
 */
export type CreateUserPayload = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * GetPollRow
 */
export type GetPollRow = {
    /**
     * Id
     */
    id: number;
    /**
     * Question
     */
    question: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Creator Name
     */
    creator_name: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Option Ids
     */
    option_ids: Array<number>;
};

/**
 * GetPollsRow
 */
export type GetPollsRow = {
    /**
     * Id
     */
    id: number;
    /**
     * Question
     */
    question: string;
    /**
     * Expires At
     */
    expires_at: string | null;
    /**
     * Creator Name
     */
    creator_name: string;
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Option Ids
     */
    option_ids: Array<number>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginPayload
 */
export type LoginPayload = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type RegisterUserUserRegisterPostData = {
    body: CreateUserPayload;
    path?: never;
    query?: never;
    url: '/user/register';
};

export type RegisterUserUserRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserUserRegisterPostError = RegisterUserUserRegisterPostErrors[keyof RegisterUserUserRegisterPostErrors];

export type RegisterUserUserRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserInfo;
};

export type RegisterUserUserRegisterPostResponse = RegisterUserUserRegisterPostResponses[keyof RegisterUserUserRegisterPostResponses];

export type LoginUserLoginPostData = {
    body: LoginPayload;
    path?: never;
    query?: never;
    url: '/user/login';
};

export type LoginUserLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginUserLoginPostError = LoginUserLoginPostErrors[keyof LoginUserLoginPostErrors];

export type LoginUserLoginPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LoginUserLoginPostResponse = LoginUserLoginPostResponses[keyof LoginUserLoginPostResponses];

export type LogoutUserLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/logout';
};

export type LogoutUserLogoutPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LogoutUserLogoutPostResponse = LogoutUserLogoutPostResponses[keyof LogoutUserLogoutPostResponses];

export type ReadUsersMeUserMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/me';
};

export type ReadUsersMeUserMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserInfo;
};

export type ReadUsersMeUserMeGetResponse = ReadUsersMeUserMeGetResponses[keyof ReadUsersMeUserMeGetResponses];

export type CreatePollPollCreatePostData = {
    body: CreatePollPayload;
    path?: never;
    query?: never;
    url: '/poll/create';
};

export type CreatePollPollCreatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePollPollCreatePostError = CreatePollPollCreatePostErrors[keyof CreatePollPollCreatePostErrors];

export type CreatePollPollCreatePostResponses = {
    /**
     * Successful Response
     */
    201: unknown;
};

export type GetAllPollsPollAllGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/poll/all';
};

export type GetAllPollsPollAllGetResponses = {
    /**
     * Response Get All Polls Poll All Get
     *
     * Successful Response
     */
    200: Array<GetPollsRow>;
};

export type GetAllPollsPollAllGetResponse = GetAllPollsPollAllGetResponses[keyof GetAllPollsPollAllGetResponses];

export type DeletePollByIdPollPollIdDeleteData = {
    body?: never;
    path: {
        /**
         * Poll Id
         */
        poll_id: number;
    };
    query?: never;
    url: '/poll/{poll_id}';
};

export type DeletePollByIdPollPollIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePollByIdPollPollIdDeleteError = DeletePollByIdPollPollIdDeleteErrors[keyof DeletePollByIdPollPollIdDeleteErrors];

export type DeletePollByIdPollPollIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePollByIdPollPollIdDeleteResponse = DeletePollByIdPollPollIdDeleteResponses[keyof DeletePollByIdPollPollIdDeleteResponses];

export type GetPollByIdPollPollIdGetData = {
    body?: never;
    path: {
        /**
         * Poll Id
         */
        poll_id: number;
    };
    query?: never;
    url: '/poll/{poll_id}';
};

export type GetPollByIdPollPollIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPollByIdPollPollIdGetError = GetPollByIdPollPollIdGetErrors[keyof GetPollByIdPollPollIdGetErrors];

export type GetPollByIdPollPollIdGetResponses = {
    /**
     * Successful Response
     */
    200: GetPollRow;
};

export type GetPollByIdPollPollIdGetResponse = GetPollByIdPollPollIdGetResponses[keyof GetPollByIdPollPollIdGetResponses];
