// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CreatePollPayload
 */
export const zCreatePollPayload = z.object({
    question: z.string(),
    options: z.array(z.string()),
    expires_at: z.union([
        z.iso.datetime(),
        z.null()
    ])
});

/**
 * CreateUserPayload
 */
export const zCreateUserPayload = z.object({
    username: z.string(),
    email: z.email(),
    password: z.string()
});

/**
 * GetPollRow
 */
export const zGetPollRow = z.object({
    id: z.int(),
    question: z.string(),
    expires_at: z.union([
        z.iso.datetime(),
        z.null()
    ]),
    creator_name: z.string(),
    options: z.array(z.string()),
    option_ids: z.array(z.int())
});

/**
 * GetPollsRow
 */
export const zGetPollsRow = z.object({
    id: z.int(),
    question: z.string(),
    expires_at: z.union([
        z.iso.datetime(),
        z.null()
    ]),
    creator_name: z.string(),
    options: z.array(z.string()),
    option_ids: z.array(z.int())
});

/**
 * LoginPayload
 */
export const zLoginPayload = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * UserInfo
 */
export const zUserInfo = z.object({
    id: z.int(),
    username: z.string(),
    email: z.email()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

export const zRegisterUserUserRegisterPostData = z.object({
    body: zCreateUserPayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zRegisterUserUserRegisterPostResponse = zUserInfo;

export const zLoginUserLoginPostData = z.object({
    body: zLoginPayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zLoginUserLoginPostResponse = z.void();

export const zLogoutUserLogoutPostData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zLogoutUserLogoutPostResponse = z.void();

export const zReadUsersMeUserMeGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zReadUsersMeUserMeGetResponse = zUserInfo;

export const zCreatePollPollCreatePostData = z.object({
    body: zCreatePollPayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetAllPollsPollAllGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get All Polls Poll All Get
 *
 * Successful Response
 */
export const zGetAllPollsPollAllGetResponse = z.array(zGetPollsRow);

export const zDeletePollByIdPollPollIdDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeletePollByIdPollPollIdDeleteResponse = z.void();

export const zGetPollByIdPollPollIdGetData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetPollByIdPollPollIdGetResponse = zGetPollRow;
