// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * CreateUserPayload
 */
export const zCreateUserPayload = z.object({
    username: z.string(),
    email: z.email(),
    password: z.string()
});

/**
 * GetPollRow
 */
export const zGetPollRow = z.object({
    id: z.int(),
    question: z.string(),
    expires_at: z.union([
        z.iso.datetime(),
        z.null()
    ]),
    creator_name: z.string(),
    options: z.array(z.string()),
    option_ids: z.array(z.int()),
    user_vote: z.unknown()
});

/**
 * GetPollsRow
 */
export const zGetPollsRow = z.object({
    id: z.int(),
    question: z.string(),
    expires_at: z.union([
        z.iso.datetime(),
        z.null()
    ]),
    creator_name: z.string(),
    options: z.array(z.string()),
    option_ids: z.array(z.int())
});

/**
 * GetVoteCountsRow
 */
export const zGetVoteCountsRow = z.object({
    vote_option_id: z.int(),
    vote_count: z.int()
});

/**
 * LoginPayload
 */
export const zLoginPayload = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * PollPerms
 */
export const zPollPerms = z.enum([
    'public_view',
    'public_vote',
    'private'
]);

/**
 * CreatePollPayload
 */
export const zCreatePollPayload = z.object({
    question: z.string(),
    options: z.array(z.string()),
    expires_at: z.union([
        z.iso.datetime(),
        z.null()
    ]),
    poll_perms: zPollPerms
});

/**
 * Role
 */
export const zRole = z.enum([
    'creator',
    'voter',
    'viewer',
    'moderator'
]);

/**
 * GetActivePollRolesRow
 */
export const zGetActivePollRolesRow = z.object({
    role: zRole,
    username: z.string()
});

/**
 * GiveAccessPayload
 */
export const zGiveAccessPayload = z.object({
    role: zRole,
    user_id: z.int()
});

/**
 * UserInfo
 */
export const zUserInfo = z.object({
    id: z.int(),
    username: z.string(),
    email: z.email()
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([
        z.string(),
        z.int()
    ])),
    msg: z.string(),
    type: z.string()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError))
});

/**
 * VotePayload
 */
export const zVotePayload = z.object({
    vote_option_id: z.int(),
    poll_id: z.int()
});

export const zRegisterUserData = z.object({
    body: zCreateUserPayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zRegisterUserResponse = zUserInfo;

export const zLoginData = z.object({
    body: zLoginPayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zLoginResponse = z.void();

export const zLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zLogoutResponse = z.void();

export const zReadUsersMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zReadUsersMeResponse = zUserInfo;

export const zCreatePollData = z.object({
    body: zCreatePollPayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zCreatePollResponse = zGetPollRow;

export const zGetAllPollsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Response Get All Polls Poll All Get
 *
 * Successful Response
 */
export const zGetAllPollsResponse = z.array(zGetPollsRow);

export const zDeletePollByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zDeletePollByIdResponse = z.void();

export const zGetPollByIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Successful Response
 */
export const zGetPollByIdResponse = zGetPollRow;

export const zAssignRoleToUserData = z.object({
    body: z.array(zGiveAccessPayload),
    path: z.optional(z.never()),
    query: z.object({
        poll_id: z.int()
    })
});

/**
 * Response Assign Role To User Poll Assign  Post
 *
 * Successful Response
 */
export const zAssignRoleToUserResponse = z.array(z.int());

export const zGetUsersForPollData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Response Get Users For Poll Poll Users Poll Id  Get
 *
 * Successful Response
 */
export const zGetUsersForPollResponse = z.array(zGetActivePollRolesRow);

export const zSubmitVoteData = z.object({
    body: zVotePayload,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetVotesForPollData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * Response Get Votes For Poll Vote  Poll Id  Get
 *
 * Successful Response
 */
export const zGetVotesForPollResponse = z.array(zGetVoteCountsRow);

export const zStreamVoteUpdatesData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        poll_id: z.int()
    }),
    query: z.optional(z.never())
});
