# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
import datetime
from typing import Optional

import pydantic


class User(pydantic.BaseModel):
    id: int
    username: str
    email: str
    password_hash: str
    created_at: Optional[datetime.datetime]
