# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.30.0
# source: user.sql
from typing import Optional

import sqlalchemy
import sqlalchemy.ext.asyncio

from app.db.sqlc import models

CREATE_USER = """-- name: create_user \\:one
INSERT INTO "user" (
    username, email, password_hash
) VALUES (
    :p1, :p2, :p3
)
RETURNING id, username, email, password_hash, created_at
"""


GET_USER = """-- name: get_user \\:one
SELECT id, username, email, password_hash, created_at FROM "user"
WHERE id = :p1 LIMIT 1
"""


GET_USER_BY_USERNAME_OR_EMAIL = """-- name: get_user_by_username_or_email \\:one
SELECT id, username, email, password_hash, created_at FROM "user"
WHERE username = :p1 OR email = :p1 LIMIT 1
"""


class AsyncQuerier:
    def __init__(self, conn: sqlalchemy.ext.asyncio.AsyncConnection):
        self._conn = conn

    async def create_user(
        self, *, username: str, email: str, password_hash: str
    ) -> Optional[models.User]:
        row = (
            await self._conn.execute(
                sqlalchemy.text(CREATE_USER),
                {"p1": username, "p2": email, "p3": password_hash},
            )
        ).first()
        if row is None:
            return None
        return models.User(
            id=row[0],
            username=row[1],
            email=row[2],
            password_hash=row[3],
            created_at=row[4],
        )

    async def get_user(self, *, id: int) -> Optional[models.User]:
        row = (await self._conn.execute(sqlalchemy.text(GET_USER), {"p1": id})).first()
        if row is None:
            return None
        return models.User(
            id=row[0],
            username=row[1],
            email=row[2],
            password_hash=row[3],
            created_at=row[4],
        )

    async def get_user_by_username_or_email(
        self, *, username: str
    ) -> Optional[models.User]:
        row = (
            await self._conn.execute(
                sqlalchemy.text(GET_USER_BY_USERNAME_OR_EMAIL), {"p1": username}
            )
        ).first()
        if row is None:
            return None
        return models.User(
            id=row[0],
            username=row[1],
            email=row[2],
            password_hash=row[3],
            created_at=row[4],
        )
